spring:
  application:
    name: muratkanov-muratbek-lalafo
lalafo:
  url: ${LALAFO_URL}
  userAgent: ${LALAFO_USER_AGENT}
  headerAccept: ${LALAFO_HEADER_ACCEPT}
  device: ${LALAFO_DEVICE}
  countryId: ${LALAFO_COUNTRY_ID}
  language: ${LALAFO_LANGUAGE}
  requestId: ${LALAFO_REQUEST_ID}
  timeout: 3000
vaadin:
  launch-browser: true
server:
  port: 9090
